kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-onprem-proxy-q1
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: 6e921c7e-7b22-4c9a-9ff6-ee3719e3c4ba #Tilgang til 0000-ga-eessi-clerk-pensjon
          - id: 79c6b5b5-1144-495c-a2c9-78aebfb5faf4 #Tilgang til 0000-ga-eessi-clerk-ufore
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: eessi-pensjon-saksbehandling-api-q1
          namespace: eessipensjon
          cluster: dev-gcp

    outbound:
      external:
        - host: pensjon-pen-q2.nais.preprod.local

  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/

    - name: LDAP_USER_BASEDN
      value: ou=NAV,ou=BusinessUnits,dc=preprod,dc=local
    - name: LDAP_SERVICEUSER_BASEDN
      value: ou=ServiceAccounts,dc=preprod,dc=local
    - name: LDAP_DOMAIN
      value: PREPROD.LOCAL
    - name: LDAP_BASEDN
      value: dc=preprod,dc=local
    - name: LDAP_URL
      value: ldaps://ldapgw.preprod.local:636
    - name: ENV
      value: q1
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-onprem-proxy-q1.dev-fss-pub.nais.io
    - https://eessi-pensjon-onprem-proxy-q1.dev.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: "4"
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 1Gi
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srveessi-pensjon-journalforing
        mountPath: /var/run/secrets/nais.io/srveessi-pensjon-journalforing-q1
      - kvPath: /serviceuser/data/dev/srveessipensjon
        mountPath: /var/run/secrets/nais.io/srveessipensjon
      - kvPath: /serviceuser/data/dev/srveessipensjonpdlp
        mountPath: /var/run/secrets/nais.io/srveessipensjonpdlp
