kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-onprem-proxy
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: eessi-pensjon-pdl-produsent
          namespace: eessipensjon
          cluster: prod-gcp
        - application: eessi-pensjon-journalforing
          namespace: eessipensjon
          cluster: prod-gcp
        - application: eessi-pensjon-krav-initialisering
          namespace: eessipensjon
          cluster: prod-gcp
        - application: eessi-pensjon-prefill
          namespace: eessipensjon
          cluster: prod-gcp
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: OPENIDCONNECT_URL
      value: https://isso.adeo.no:443/isso
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: AZURE_APP_FAGMODUL_CLIENT_ID
      value: prod-gcp.eessipensjon.eessi-pensjon-fagmodul
    - name: FAGMODUL_URL
      value: https://eessi-pensjon-fagmodul.nais.adeo.no
    - name: NORG2_URL
      value: https://app.adeo.no/norg2
    - name: KODEVERK_REST_API_URL
      value: https://kodeverk.nais.adeo.no
    - name: PENSJONSINFORMASJON_URL
      value: https://pensjon-pen.nais.adeo.no/pen/api/pensjonsinformasjon/v1
    - name: PENSJON_BEHANDLEHENDELSE_URL
      value: https://pensjon-pen.nais.adeo.no/pen/api/behandlehendelse/utland/v1/
    - name: BESTEMSAK_URL
      value: https://pensjon-pen.nais.adeo.no/pen/api/bestemsak/v1
    - name: PDL_PERSON_MOTTAK_URL
      value: https://person-mottak.nais.adeo.no
    - name: LDAP_DOMAIN
      value: ADEO.NO
    - name: LDAP_BASEDN
      value: dc=adeo,dc=no
    - name: LDAP_URL
      value: ldaps://ldapgw.adeo.no
    - name: LDAP_USER_BASEDN
      value: ou=NAV,ou=BusinessUnits,dc=adeo,dc=no
    - name: LDAP_SERVICEUSER_BASEDN
      value: ou=ServiceAccounts,dc=adeo,dc=no
    - name: ENV
      value: p
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-onprem-proxy.prod-fss-pub.nais.io
    - https://eessi-pensjon-onprem-proxy.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srveessi-pensjon-journalforing
        mountPath: /var/run/secrets/nais.io/srveessi-pensjon-journalforing
      - kvPath: /serviceuser/data/prod/srveessipensjon
        mountPath: /var/run/secrets/nais.io/srveessipensjon
      - kvPath: /serviceuser/data/prod/srveessipensjonpdlp
        mountPath: /var/run/secrets/nais.io/srveessipensjonpdlp

