name: Bygg branch og publiser

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!main'

jobs:
  bygg_og_publiser:
    name: 'Bygg branch og publiser image'
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    runs-on: ubuntu-latest
    env:
      package: eessi-pensjon-onprem-proxy
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v3

      - name: 'Java'
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: 'Sjekker at bygget kjører'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TZ=CET
          ./gradlew build --stacktrace

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: eessipensjon
          tag: onprem-proxy
          pull: true
          dockerfile: Dockerfile
          image_suffix: ${{ env.DATE }}${{ env.COMMIT_HASH }} # optional, default empty
          cache_from: type=gha # optional, default type=gha
          cache_to: type=gha,mode=max # optional, default type=gha,mode=max
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret

      - name: 'Deploy image'
        run: echo "IMAGE=${{ steps.docker-push.outputs.image }}"

      - name: 'Deploy to FSS'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss.yml
          IMAGE: ${{ steps.docker-push.outputs.image }}

      - name: 'Opprett git tag'
        run: |
          curl -v -s -X POST https://api.github.com/repos/${{ github.repository }}/git/refs -H "Authorization: token  ${{ secrets.GITHUB_TOKEN }}" -d '{ "ref": "refs/tags/${{ env.DATE }}---${{ env.COMMIT_HASH }}",  "sha": "${{ env.COMMIT_HASH }}" }'

      - name: 'Echo Image Name'
        run: echo "### Image Name ${{ steps.docker-push.outputs.image }}" >> $GITHUB_STEP_SUMMARY
