name: Bygg branch og publiser

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!main'

jobs:
  bygg_og_publiser:
    name: 'Bygg branch og publiser image'
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    runs-on: ubuntu-latest
    env:
      package: eessi-pensjon-onprem-proxy
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v3

      - name: 'Java'
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: 'Setter Image'
        run: echo "IMAGE=ghcr.io/${{ github.repository }}/${{ env.package }}:${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      - name: 'Bygg og publiser docker image'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TZ=CET
          ./gradlew build --stacktrace
          docker build --tag ${{ env.IMAGE }} .
          docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE }}

      - name: 'Image navn'
        run: echo "IMAGE=${{ env.DOCKER_METADATA_OUTPUT_TAGS }}"

      - name: 'Echo Image Name'
        run: echo "### Image Hash $(echo ${{  env.DOCKER_METADATA_OUTPUT_TAGS }} | cut -d':' -f2)" >> $GITHUB_STEP_SUMMARY
