name: Deploy PROD (FSS)
on:
  repository_dispatch:
    types: [deploy-prod]

jobs:
  deploy_prod:
    name: 'Deploy til PROD (FSS)'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v4

      - name: 'Vise image'
        run: |
          echo "image-tag: ${{ github.event.client_payload.image }}"

      - name: 'NAIS-deploy to PROD (FSS)'
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/prod-fss.yml
          IMAGE: ${{ github.event.client_payload.image }}
